services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - tp1_net
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10


  2000s-filter-1:
    container_name: 2000s-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=2000s_filter
      - FILTER_NUM=1
      - SHARDS=2
    networks:
      - tp1_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10
#    tmpfs:
#      - /tmp/states
    volumes:
      - /tmp/states:/tmp/states
    depends_on:

      ar-es-filter-1:
        condition: service_healthy
      ar-es-filter-2:
        condition: service_healthy
      ar-filter-1:
        condition: service_healthy
      ar-filter-2:
        condition: service_healthy
  2000s-filter-2:
    container_name: 2000s-filter-2
    image: filter:latest
    environment:
      - FILTER_TYPE=2000s_filter
      - FILTER_NUM=2
      - SHARDS=2
    networks:
      - tp1_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10
#    tmpfs:
#      - /tmp/states
    volumes:
      - /tmp/states:/tmp/states
    depends_on:

      ar-es-filter-1:
        condition: service_healthy
      ar-es-filter-2:
        condition: service_healthy
      ar-filter-1:
        condition: service_healthy
      ar-filter-2:
        condition: service_healthy


  ar-es-filter-1:
    container_name: ar-es-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=ar_es_filter
      - FILTER_NUM=1
      - SHARDS=2
    networks:
      - tp1_net
    depends_on:
      aggregator_movies:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  ar-es-filter-2:
    container_name: ar-es-filter-2
    image: filter:latest
    environment:
      - FILTER_TYPE=ar_es_filter
      - FILTER_NUM=2
      - SHARDS=2
    networks:
      - tp1_net
    depends_on:
      aggregator_movies:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10



  ar-filter-1:
    container_name: ar-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=ar_filter
      - FILTER_NUM=1
      - SHARDS=2
    networks:
      - tp1_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:

      joiner_group_by_movie_id_credits-1:
        condition: service_healthy
      joiner_group_by_movie_id_ratings-1:
        condition: service_healthy
      joiner_group_by_movie_id_credits-2:
        condition: service_healthy
      joiner_group_by_movie_id_ratings-2:
        condition: service_healthy

  ar-filter-2:
    container_name: ar-filter-2
    image: filter:latest
    environment:
      - FILTER_TYPE=ar_filter
      - FILTER_NUM=2
      - SHARDS=2
    networks:
      - tp1_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:

      joiner_group_by_movie_id_credits-1:
        condition: service_healthy
      joiner_group_by_movie_id_ratings-1:
        condition: service_healthy
      joiner_group_by_movie_id_credits-2:
        condition: service_healthy
      joiner_group_by_movie_id_ratings-2:
        condition: service_healthy



  single-country-origin-filter-1:
    container_name: single-country-origin-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=single_country_origin_filter
      - FILTER_NUM=1
      - SHARDS=2
      - FILTER_NODES=2
      - NODE_NAME=single-country-origin-filter-1
    networks:
      - tp1_net
    depends_on:
      aggregator_top_5:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  single-country-origin-filter-2:
    container_name: single-country-origin-filter-2
    image: filter:latest
    environment:
      - FILTER_TYPE=single_country_origin_filter
      - FILTER_NUM=2
      - SHARDS=2
      - FILTER_NODES=2
      - NODE_NAME=single-country-origin-filter-2
    networks:
      - tp1_net
    depends_on:
      aggregator_top_5:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10



  joiner_group_by_movie_id_ratings-1:
    container_name: joiner_group_by_movie_id_ratings-1
    image: joiner:latest
    environment:
      - JOINER_TYPE=group_by_movie_id_ratings
      - JOINER_ID=1
      - JOINER_INPUT_QUEUE_BASE_NAME=ar_movies_2000_and_later
      - JOINER_INPUT_QUEUE_SEC_NAME=ratings_1
      - JOINER_OUTPUT_QUEUE_NAME=movies_top_and_bottom
    networks:
      - tp1_net
    depends_on:
      aggregator_top_and_bottom:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  joiner_group_by_movie_id_ratings-2:
    container_name: joiner_group_by_movie_id_ratings-2
    image: joiner:latest
    environment:
      - JOINER_TYPE=group_by_movie_id_ratings
      - JOINER_ID=2
      - JOINER_INPUT_QUEUE_BASE_NAME=ar_movies_2000_and_later
      - JOINER_INPUT_QUEUE_SEC_NAME=ratings_2
      - JOINER_OUTPUT_QUEUE_NAME=movies_top_and_bottom
    networks:
      - tp1_net
    depends_on:
      aggregator_top_and_bottom:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10



  joiner_group_by_movie_id_credits-1:
    container_name: joiner_group_by_movie_id_credits-1
    image: joiner:latest
    environment:
      - JOINER_TYPE=group_by_movie_id_credits
      - JOINER_ID=1
      - JOINER_INPUT_QUEUE_BASE_NAME=ar_movies_after_2000
      - JOINER_INPUT_QUEUE_SEC_NAME=credits_1
      - JOINER_OUTPUT_QUEUE_NAME=actor_movies_count
    networks:
      - tp1_net
    depends_on:
      aggregator_top_10:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  joiner_group_by_movie_id_credits-2:
    container_name: joiner_group_by_movie_id_credits-2
    image: joiner:latest
    environment:
      - JOINER_TYPE=group_by_movie_id_credits
      - JOINER_ID=2
      - JOINER_INPUT_QUEUE_BASE_NAME=ar_movies_after_2000
      - JOINER_INPUT_QUEUE_SEC_NAME=credits_2
      - JOINER_OUTPUT_QUEUE_NAME=actor_movies_count
    networks:
      - tp1_net
    depends_on:
      aggregator_top_10:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10


  aggregator_movies:
    container_name: aggregator_movies
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=movies
      - AGGREGATOR_ID=1
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=movies_ar_es_2000s
      - AGGREGATOR_OUTPUT_QUEUE_NAME=movies_report
    networks:
      - tp1_net
    depends_on:
      report:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  aggregator_top_5:
    container_name: aggregator_top_5
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=top_5
      - AGGREGATOR_ID=2
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=single_country_origin_movies
      - AGGREGATOR_OUTPUT_QUEUE_NAME=top_5_report
    networks:
      - tp1_net
    depends_on:
      report:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  aggregator_top_10:
    container_name: aggregator_top_10
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=top_10
      - AGGREGATOR_ID=3
      - AGGREGATOR_AMOUNT_SOURCES=2
      - AGGREGATOR_INPUT_QUEUE_NAME=actor_movies_count
      - AGGREGATOR_OUTPUT_QUEUE_NAME=top_10_report
    networks:
      - tp1_net
    depends_on:
      report:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  aggregator_top_and_bottom:
    container_name: aggregator_top_and_bottom
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=top_and_bottom
      - AGGREGATOR_ID=4
      - AGGREGATOR_AMOUNT_SOURCES=2
      - AGGREGATOR_INPUT_QUEUE_NAME=movies_top_and_bottom
      - AGGREGATOR_OUTPUT_QUEUE_NAME=top_and_bottom_report
    networks:
      - tp1_net
    depends_on:
      report:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  aggregator_metrics:
    container_name: aggregator_metrics
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=metrics
      - AGGREGATOR_ID=5
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=negative_movies
      - AGGREGATOR_INPUT_QUEUE_SEC_NAME=positive_movies
      - AGGREGATOR_OUTPUT_QUEUE_NAME=metrics_report
    networks:
      - tp1_net
    depends_on:
      report:
        condition: service_healthy
    links:
      - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10


  nlp-1:
    container_name: nlp-1
    image: nlp:latest
    environment:
      - NODE_NUM=1
      - SHARDS=2
      - NLP_NODES=2
      - NODE_NAME=nlp-1
    networks:
      - tp1_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./nlp-cache:/app/cache

  nlp-2:
    container_name: nlp-2
    image: nlp:latest
    environment:
      - NODE_NUM=2
      - SHARDS=2
      - NLP_NODES=2
      - NODE_NAME=nlp-2
    networks:
      - tp1_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./nlp-cache:/app/cache


  controller:
    container_name: controller
    image: controller:latest
    build:
      context: .
      dockerfile: src/server/gateway/Dockerfile
    environment:
      - SHARDS=2
    networks:
      - tp1_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      2000s-filter-1:
        condition: service_healthy
      2000s-filter-2:
        condition: service_healthy
      single-country-origin-filter-1:
        condition: service_healthy
      single-country-origin-filter-2:
        condition: service_healthy
      joiner_group_by_movie_id_credits-1:
        condition: service_healthy
      joiner_group_by_movie_id_ratings-1:
        condition: service_healthy
      joiner_group_by_movie_id_credits-2:
        condition: service_healthy
      joiner_group_by_movie_id_ratings-2:
        condition: service_healthy
      nlp-1:
        condition: service_started
      nlp-2:
        condition: service_started


  client-1:
    container_name: client-1
    image: client:latest
    build:
      context: .
      dockerfile: src/client/Dockerfile
    networks:
      - tp1_net
    depends_on:
      controller:
        condition: service_healthy
    volumes:
      - ./src/client/datasets:/app/datasets
      - ./reports:/app
    entrypoint: /client
    command:
      - /app/datasets/movies.csv
      - /app/datasets/ratings.csv
      - /app/datasets/credits.csv

  client-2:
    container_name: client-2
    image: client:latest
    build:
      context: .
      dockerfile: src/client/Dockerfile
    networks:
      - tp1_net
    depends_on:
      controller:
        condition: service_healthy
    volumes:
      - ./src/client/datasets:/app/datasets
      - ./reports:/app
    entrypoint: /client
    command:
      - /app/datasets/movies.csv
      - /app/datasets/ratings.csv
      - /app/datasets/credits.csv


  report:
    build:
      context: .
      dockerfile: src/server/report/Dockerfile
    container_name: report
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - tp1_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 10s
      retries: 10

  resilience_manager:
    container_name: resilience_manager
    image: resilience_manager:latest
    build:
      context: .
      dockerfile: src/server/resilience_manager/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tp1_net
    depends_on:
      controller:
        condition: service_healthy
    environment:
      - RESILIENCE_CHECK_INTERVAL=5
      - RESILIENCE_UNHEALTHY_THRESHOLD=3
      - RESILIENCE_RESTART_WAIT=15
      - HEALTH_ENDPOINT=/ping

      - MONITOR_SERVICE_FILTER_1=2000s-filter-1
      - MONITOR_SERVICE_FILTER_2=2000s-filter-2

      - MONITOR_SERVICE_FILTER_3=ar-es-filter-1
      - MONITOR_SERVICE_FILTER_4=ar-es-filter-2

      - MONITOR_SERVICE_FILTER_5=ar-filter-1
      - MONITOR_SERVICE_FILTER_6=ar-filter-2

      - MONITOR_SERVICE_FILTER_7=single-country-origin-filter-1
      - MONITOR_SERVICE_FILTER_8=single-country-origin-filter-2

      - MONITOR_SERVICE_JOINER_1=joiner_group_by_movie_id_ratings-1
      - MONITOR_SERVICE_JOINER_2=joiner_group_by_movie_id_ratings-2

      - MONITOR_SERVICE_JOINER_3=joiner_group_by_movie_id_credits-1
      - MONITOR_SERVICE_JOINER_4=joiner_group_by_movie_id_credits-2
      - MONITOR_SERVICE_AGGREGATOR_1=aggregator_movies
      - MONITOR_SERVICE_AGGREGATOR_2=aggregator_top_5
      - MONITOR_SERVICE_AGGREGATOR_3=aggregator_top_10
      - MONITOR_SERVICE_AGGREGATOR_4=aggregator_top_and_bottom
      - MONITOR_SERVICE_AGGREGATOR_5=aggregator_metrics

      - MONITOR_SERVICE_CONTROLLER_1=controller
      - MONITOR_SERVICE_REPORT_1=report
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/ping | grep -q pong" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24