services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - tp1_net


  2000s-filter-1:
    container_name: 2000s-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=2000s_filter
      - FILTER_NUM=1
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq



  ar-es-filter-1:
    container_name: ar-es-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=ar_es_filter
      - FILTER_NUM=1
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq



  ar-filter-1:
    container_name: ar-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=ar_filter
      - FILTER_NUM=1
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq



  single-country-origin-filter-1:
    container_name: single-country-origin-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=single_country_origin_filter
      - FILTER_NUM=1
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq



  top-5-investors-filter-1:
    container_name: top-5-investors-filter-1
    image: filter:latest
    environment:
      - FILTER_TYPE=top_5_investors_filter
      - FILTER_NUM=1
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq


  joiner_group_by_movie_id_ratings:
    container_name: joiner_group_by_movie_id_ratings
    image: joiner:latest
    environment:
      - JOINER_TYPE=group_by_movie_id_ratings
      - JOINER_ID=1
      - JOINER_INPUT_QUEUE_BASE_NAME=ar_movies_2000_and_later
      - JOINER_INPUT_QUEUE_SEC_NAME=ratings
      - JOINER_OUTPUT_QUEUE_NAME=movies_top_and_bottom
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  joiner_group_by_movie_id_credits:
    container_name: joiner_group_by_movie_id_credits
    image: joiner:latest
    environment:
      - JOINER_TYPE=group_by_movie_id_credits
      - JOINER_ID=1
      - JOINER_INPUT_QUEUE_BASE_NAME=ar_movies_2000_and_later
      - JOINER_INPUT_QUEUE_SEC_NAME=credits
      - JOINER_OUTPUT_QUEUE_NAME=actor_movies_count
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  aggregator_movies:
    container_name: aggregator_movies
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=movies
      - AGGREGATOR_ID=1
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=movies_ar_es_2000s
      - AGGREGATOR_OUTPUT_QUEUE_NAME=movies_report
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  aggregator_top_5:
    container_name: aggregator_top_5
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=top_5
      - AGGREGATOR_ID=2
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=movies_top_5_investors
      - AGGREGATOR_OUTPUT_QUEUE_NAME=top_5_report
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  aggregator_top_10:
    container_name: aggregator_top_10
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=top_10
      - AGGREGATOR_ID=3
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=actor_movies_count
      - AGGREGATOR_OUTPUT_QUEUE_NAME=top_10_report
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  aggregator_top_and_bottom:
    container_name: aggregator_top_and_bottom
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=top_and_bottom
      - AGGREGATOR_ID=4
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=movies_top_and_bottom
      - AGGREGATOR_OUTPUT_QUEUE_NAME=top_and_bottom_report
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  aggregator_metrics:
    container_name: aggregator_metrics
    image: aggregator:latest
    environment:
      - AGGREGATOR_TYPE=metrics
      - AGGREGATOR_ID=5
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=negative_movies
      - AGGREGATOR_INPUT_QUEUE_SEC_NAME=positive_movies
      - AGGREGATOR_OUTPUT_QUEUE_NAME=metrics_report
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
    links:
      - rabbitmq


  nlp-1:
    container_name: nlp-1
    image: nlp:latest
    environment:
      - NODE_NUM=1
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq

  nlp-2:
    container_name: nlp-2
    image: nlp:latest
    environment:
      - NODE_NUM=2
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq

  nlp-3:
    container_name: nlp-3
    image: nlp:latest
    environment:
      - NODE_NUM=3
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq

  nlp-4:
    container_name: nlp-4
    image: nlp:latest
    environment:
      - NODE_NUM=4
      - SHARDS=1
    networks:
      - tp1_net
    depends_on:
      - rabbitmq


  controller:
    container_name: controller
    image: controller:latest
    build:
      context: .
      dockerfile: src/server/gateway/Dockerfile
    networks:
      - tp1_net
    depends_on:
      - rabbitmq
      - aggregator_metrics
      - aggregator_top_and_bottom
      - aggregator_top_10
      - aggregator_top_5
      - aggregator_movies
      - joiner_group_by_movie_id_credits
      - joiner_group_by_movie_id_ratings
      - report
      - 2000s-filter-1
      - ar-es-filter-1
      - ar-filter-1
      - top-5-investors-filter-1
      - single-country-origin-filter-1
      - nlp-1
      - nlp-2
      - nlp-3
      - nlp-4

  client:
    container_name: client
    image: client:latest
    build:
      context: .
      dockerfile: src/client/Dockerfile
    networks:
      - tp1_net
    depends_on:
      - controller
    volumes:
      - ./src/client/datasets:/app/datasets
      - ./reports:/app
    entrypoint: /client
    command:
      - /app/datasets/movies.csv
      - /app/datasets/ratings.csv
      - /app/datasets/credits.csv

  report:
    build:
      context: .
      dockerfile: src/server/report/Dockerfile
    container_name: report
    depends_on:
      - rabbitmq
    networks:
      - tp1_net

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24