services:

  rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      ports:
          # Web Panel port
          - "15672:15672"
          - "5672:5672"
      environment:
          # To log in at web panel
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin
      volumes:
          - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      networks:
          - testing_net
  
  test:
    container_name: app-test
    image: app-test:latest
    restart: on-failure
    environment:
      - AGGREGATOR_TYPE=movies
      - AGGREGATOR_AMQP_URL=amqp://admin:admin@rabbitmq:5672/
      - AGGREGATOR_ID=1
      - AGGREGATOR_AMOUNT_SOURCES=1
      - AGGREGATOR_INPUT_QUEUE_NAME=movies_aggregator
      - AGGREGATOR_OUTPUT_QUEUE_NAME=movies_report
    networks:
      - testing_net
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24