services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            # Web Panel port
            - "15672:15672"
        environment:
            # To log in at web panel
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        networks:
            - tp1_net

    2000s-filter-1:
        container_name: 2000s-filter-1
        image: filter:latest
        environment:
            - FILTER_TYPE=2000s_filter
            - FILTER_NUM=1
        networks:
            - tp1_net
        depends_on:
            # TODO: esto solo asegura que el container de rabbitmq se levante primero, no que esté funcionando
            - rabbitmq 

    ar-es-filter-1:
        container_name: ar-es-filter-1
        image: filter:latest
        environment:
            - FILTER_TYPE=ar_es_filter
            - FILTER_NUM=1
        networks:
            - tp1_net
        depends_on:
            - rabbitmq 

    ar-filter-1:
        container_name: ar-filter-1
        image: filter:latest
        environment:
            - FILTER_TYPE=ar_filter
            - FILTER_NUM=1
        networks:
            - tp1_net
        depends_on:
            - rabbitmq 

    top-5-investors-filter-1:
        container_name: top-5-investors-filter-1
        image: filter:latest
        environment:
            - FILTER_TYPE=top-5-investors-filter
            - FILTER_NUM=1
        networks:
            - tp1_net
        depends_on:
            - rabbitmq 

    nlp-1:
        container_name: nlp-1
        image: nlp:latest
        environment:
            - NODE_NUM=1
        networks:
            - tp1_net
        depends_on:
            - rabbitmq 

    controller:
        container_name: controller
        image: controller:latest
        build:
            context: .
            dockerfile: src/server/gateway/Dockerfile
        networks:
            - tp1_net
        depends_on:
            - rabbitmq
            - 2000s-filter-1
            - ar-es-filter-1
            - ar-filter-1
            - top-5-investors-filter-1
            - nlp-1

    client:
        container_name: client
        image: client:latest
        build:
            context: .
            dockerfile: src/client/Dockerfile
        networks:
            - tp1_net
        depends_on:
            - controller
        volumes:
            - ./src/client/datasets:/app/datasets
        entrypoint: /client
        command:
            - /app/datasets/movies.csv
            - /app/datasets/ratings.csv
            - /app/datasets/credits.csv
        restart: on-failure

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
