FROM golang:1.24.1

# Set the working directory inside the container
WORKDIR /app

# Copy the go mod and sum files
COPY ./src/go.mod ./
COPY ./src/go.sum ./

# Download all dependencies
RUN go mod download 

# Copy the source from the current directory to the working directory inside the container
COPY ./src .

EXPOSE 3000

# Command to run the tests
CMD ["go", "test", "-v", "./..."]