# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie_sanit.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'movie_sanit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11movie_sanit.proto\"\xe2\x01\n\nMovieSanit\x12\x0e\n\x06\x62udget\x18\x01 \x02(\x03\x12\x0e\n\x06genres\x18\x02 \x03(\t\x12\n\n\x02id\x18\x03 \x02(\x05\x12\x10\n\x08overview\x18\x04 \x02(\t\x12\x1c\n\x14production_countries\x18\x05 \x03(\t\x12\x14\n\x0crelease_year\x18\x06 \x02(\r\x12\x0f\n\x07revenue\x18\x07 \x02(\x01\x12\r\n\x05title\x18\x08 \x02(\t\x12\x10\n\x08\x63lientId\x18\t \x02(\t\x12\x11\n\tmessageId\x18\n \x02(\x03\x12\x10\n\x08sourceId\x18\x0b \x01(\t\x12\x0b\n\x03\x65of\x18\x0c \x01(\x08\x42\x0bZ\t./protopb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_sanit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./protopb'
  _globals['_MOVIESANIT']._serialized_start=22
  _globals['_MOVIESANIT']._serialized_end=248
# @@protoc_insertion_point(module_scope)
