# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie_sanit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11movie_sanit.proto\"\xab\x01\n\nMovieSanit\x12\x0e\n\x06\x62udget\x18\x01 \x02(\x05\x12\x0e\n\x06genres\x18\x02 \x03(\t\x12\n\n\x02id\x18\x03 \x02(\x05\x12\x10\n\x08overview\x18\x04 \x02(\t\x12\x1c\n\x14production_countries\x18\x05 \x03(\t\x12\x14\n\x0crelease_year\x18\x06 \x02(\r\x12\x0f\n\x07revenue\x18\x07 \x02(\x01\x12\r\n\x05title\x18\x08 \x02(\t\x12\x0b\n\x03\x65of\x18\t \x01(\x08\x42\x0bZ\t./protopb')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_sanit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t./protopb'
  _MOVIESANIT._serialized_start=22
  _MOVIESANIT._serialized_end=193
# @@protoc_insertion_point(module_scope)
