id: "1"
amqp_url: "amqp://admin:admin@rabbitmq:5672/"
amount_sources: 1
input_queue:  
  delete_when_unused: false
  durable: false
  exclusive: false	
  name: "AggregatorMovies"	
  no_wait: false
output_queue:
  delete_when_unused: false
  durable: false
  exclusive: false	
  name: "AggregatorReport"	
  no_wait: false
