// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: coordination.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_LEADER MessageType = 0
	MessageType_ACK    MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "LEADER",
		1: "ACK",
	}
	MessageType_value = map[string]int32{
		"LEADER": 0,
		"ACK":    1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_coordination_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_coordination_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MessageType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MessageType(num)
	return nil
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{0}
}

type CoordinationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,req,name=client_id,json=clientId" json:"client_id,omitempty"`
	NodeId        *string                `protobuf:"bytes,2,req,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Type          *MessageType           `protobuf:"varint,3,req,name=type,enum=coordination.MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinationMessage) Reset() {
	*x = CoordinationMessage{}
	mi := &file_coordination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinationMessage) ProtoMessage() {}

func (x *CoordinationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinationMessage.ProtoReflect.Descriptor instead.
func (*CoordinationMessage) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinationMessage) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *CoordinationMessage) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *CoordinationMessage) GetType() MessageType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MessageType_LEADER
}

var File_coordination_proto protoreflect.FileDescriptor

const file_coordination_proto_rawDesc = "" +
	"\n" +
	"\x12coordination.proto\x12\fcoordination\"z\n" +
	"\x13CoordinationMessage\x12\x1b\n" +
	"\tclient_id\x18\x01 \x02(\tR\bclientId\x12\x17\n" +
	"\anode_id\x18\x02 \x02(\tR\x06nodeId\x12-\n" +
	"\x04type\x18\x03 \x02(\x0e2\x19.coordination.MessageTypeR\x04type*\"\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06LEADER\x10\x00\x12\a\n" +
	"\x03ACK\x10\x01B\vZ\t./protopb"

var (
	file_coordination_proto_rawDescOnce sync.Once
	file_coordination_proto_rawDescData []byte
)

func file_coordination_proto_rawDescGZIP() []byte {
	file_coordination_proto_rawDescOnce.Do(func() {
		file_coordination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordination_proto_rawDesc), len(file_coordination_proto_rawDesc)))
	})
	return file_coordination_proto_rawDescData
}

var file_coordination_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coordination_proto_goTypes = []any{
	(MessageType)(0),            // 0: coordination.MessageType
	(*CoordinationMessage)(nil), // 1: coordination.CoordinationMessage
}
var file_coordination_proto_depIdxs = []int32{
	0, // 0: coordination.CoordinationMessage.type:type_name -> coordination.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coordination_proto_init() }
func file_coordination_proto_init() {
	if File_coordination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordination_proto_rawDesc), len(file_coordination_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coordination_proto_goTypes,
		DependencyIndexes: file_coordination_proto_depIdxs,
		EnumInfos:         file_coordination_proto_enumTypes,
		MessageInfos:      file_coordination_proto_msgTypes,
	}.Build()
	File_coordination_proto = out.File
	file_coordination_proto_goTypes = nil
	file_coordination_proto_depIdxs = nil
}
