// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: credit_sanit.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditSanit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CastNames     []string               `protobuf:"bytes,1,rep,name=castNames" json:"castNames,omitempty"`
	ProfilePaths  []string               `protobuf:"bytes,2,rep,name=profilePaths" json:"profilePaths,omitempty"`
	Id            *int64                 `protobuf:"varint,3,req,name=id" json:"id,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,req,name=clientId" json:"clientId,omitempty"`
	MessageId     *int64                 `protobuf:"varint,5,req,name=messageId" json:"messageId,omitempty"`
	Eof           *bool                  `protobuf:"varint,6,opt,name=eof" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditSanit) Reset() {
	*x = CreditSanit{}
	mi := &file_credit_sanit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditSanit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditSanit) ProtoMessage() {}

func (x *CreditSanit) ProtoReflect() protoreflect.Message {
	mi := &file_credit_sanit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditSanit.ProtoReflect.Descriptor instead.
func (*CreditSanit) Descriptor() ([]byte, []int) {
	return file_credit_sanit_proto_rawDescGZIP(), []int{0}
}

func (x *CreditSanit) GetCastNames() []string {
	if x != nil {
		return x.CastNames
	}
	return nil
}

func (x *CreditSanit) GetProfilePaths() []string {
	if x != nil {
		return x.ProfilePaths
	}
	return nil
}

func (x *CreditSanit) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CreditSanit) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *CreditSanit) GetMessageId() int64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *CreditSanit) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_credit_sanit_proto protoreflect.FileDescriptor

const file_credit_sanit_proto_rawDesc = "" +
	"\n" +
	"\x12credit_sanit.proto\"\xab\x01\n" +
	"\vCreditSanit\x12\x1c\n" +
	"\tcastNames\x18\x01 \x03(\tR\tcastNames\x12\"\n" +
	"\fprofilePaths\x18\x02 \x03(\tR\fprofilePaths\x12\x0e\n" +
	"\x02id\x18\x03 \x02(\x03R\x02id\x12\x1a\n" +
	"\bclientId\x18\x04 \x02(\tR\bclientId\x12\x1c\n" +
	"\tmessageId\x18\x05 \x02(\x03R\tmessageId\x12\x10\n" +
	"\x03eof\x18\x06 \x01(\bR\x03eofB\vZ\t./protopb"

var (
	file_credit_sanit_proto_rawDescOnce sync.Once
	file_credit_sanit_proto_rawDescData []byte
)

func file_credit_sanit_proto_rawDescGZIP() []byte {
	file_credit_sanit_proto_rawDescOnce.Do(func() {
		file_credit_sanit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credit_sanit_proto_rawDesc), len(file_credit_sanit_proto_rawDesc)))
	})
	return file_credit_sanit_proto_rawDescData
}

var file_credit_sanit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_credit_sanit_proto_goTypes = []any{
	(*CreditSanit)(nil), // 0: CreditSanit
}
var file_credit_sanit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_credit_sanit_proto_init() }
func file_credit_sanit_proto_init() {
	if File_credit_sanit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credit_sanit_proto_rawDesc), len(file_credit_sanit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_credit_sanit_proto_goTypes,
		DependencyIndexes: file_credit_sanit_proto_depIdxs,
		MessageInfos:      file_credit_sanit_proto_msgTypes,
	}.Build()
	File_credit_sanit_proto = out.File
	file_credit_sanit_proto_goTypes = nil
	file_credit_sanit_proto_depIdxs = nil
}
