// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: credit.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cast          *string                `protobuf:"bytes,1,req,name=cast" json:"cast,omitempty"`
	Id            *int64                 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	ClientId      *string                `protobuf:"bytes,3,opt,name=clientId" json:"clientId,omitempty"`
	Eof           *bool                  `protobuf:"varint,4,opt,name=eof" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credit) Reset() {
	*x = Credit{}
	mi := &file_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credit) ProtoMessage() {}

func (x *Credit) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credit.ProtoReflect.Descriptor instead.
func (*Credit) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{0}
}

func (x *Credit) GetCast() string {
	if x != nil && x.Cast != nil {
		return *x.Cast
	}
	return ""
}

func (x *Credit) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Credit) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Credit) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_credit_proto protoreflect.FileDescriptor

const file_credit_proto_rawDesc = "" +
	"\n" +
	"\fcredit.proto\x1a\x1bgoogle/protobuf/empty.proto\"Z\n" +
	"\x06Credit\x12\x12\n" +
	"\x04cast\x18\x01 \x02(\tR\x04cast\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\x03R\x02id\x12\x1a\n" +
	"\bclientId\x18\x03 \x01(\tR\bclientId\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof2C\n" +
	"\rCreditService\x122\n" +
	"\rStreamCredits\x12\a.Credit\x1a\x16.google.protobuf.Empty(\x01B\vZ\t./protopb"

var (
	file_credit_proto_rawDescOnce sync.Once
	file_credit_proto_rawDescData []byte
)

func file_credit_proto_rawDescGZIP() []byte {
	file_credit_proto_rawDescOnce.Do(func() {
		file_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credit_proto_rawDesc), len(file_credit_proto_rawDesc)))
	})
	return file_credit_proto_rawDescData
}

var file_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_credit_proto_goTypes = []any{
	(*Credit)(nil),        // 0: Credit
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_credit_proto_depIdxs = []int32{
	0, // 0: CreditService.StreamCredits:input_type -> Credit
	1, // 1: CreditService.StreamCredits:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_credit_proto_init() }
func file_credit_proto_init() {
	if File_credit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credit_proto_rawDesc), len(file_credit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credit_proto_goTypes,
		DependencyIndexes: file_credit_proto_depIdxs,
		MessageInfos:      file_credit_proto_msgTypes,
	}.Build()
	File_credit_proto = out.File
	file_credit_proto_goTypes = nil
	file_credit_proto_depIdxs = nil
}
