// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: metrics.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metrics struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AvgRevenueOverBudgetNegative *float64               `protobuf:"fixed64,1,req,name=avgRevenueOverBudgetNegative" json:"avgRevenueOverBudgetNegative,omitempty"`
	AvgRevenueOverBudgetPositive *float64               `protobuf:"fixed64,2,req,name=avgRevenueOverBudgetPositive" json:"avgRevenueOverBudgetPositive,omitempty"`
	ClientId                     *string                `protobuf:"bytes,3,req,name=clientId" json:"clientId,omitempty"`
	MessageId                    *int64                 `protobuf:"varint,4,req,name=messageId" json:"messageId,omitempty"`
	Eof                          *bool                  `protobuf:"varint,5,opt,name=eof" json:"eof,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metrics) GetAvgRevenueOverBudgetNegative() float64 {
	if x != nil && x.AvgRevenueOverBudgetNegative != nil {
		return *x.AvgRevenueOverBudgetNegative
	}
	return 0
}

func (x *Metrics) GetAvgRevenueOverBudgetPositive() float64 {
	if x != nil && x.AvgRevenueOverBudgetPositive != nil {
		return *x.AvgRevenueOverBudgetPositive
	}
	return 0
}

func (x *Metrics) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Metrics) GetMessageId() int64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *Metrics) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\"\xdd\x01\n" +
	"\aMetrics\x12B\n" +
	"\x1cavgRevenueOverBudgetNegative\x18\x01 \x02(\x01R\x1cavgRevenueOverBudgetNegative\x12B\n" +
	"\x1cavgRevenueOverBudgetPositive\x18\x02 \x02(\x01R\x1cavgRevenueOverBudgetPositive\x12\x1a\n" +
	"\bclientId\x18\x03 \x02(\tR\bclientId\x12\x1c\n" +
	"\tmessageId\x18\x04 \x02(\x03R\tmessageId\x12\x10\n" +
	"\x03eof\x18\x05 \x01(\bR\x03eofB\vZ\t./protopb"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metrics_proto_goTypes = []any{
	(*Metrics)(nil), // 0: Metrics
}
var file_metrics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
