// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: movie_sanit.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieSanit struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Budget              *int32                 `protobuf:"varint,1,req,name=budget" json:"budget,omitempty"`
	Genres              []string               `protobuf:"bytes,2,rep,name=genres" json:"genres,omitempty"`
	Id                  *int32                 `protobuf:"varint,3,req,name=id" json:"id,omitempty"`
	Overview            *string                `protobuf:"bytes,4,req,name=overview" json:"overview,omitempty"`
	ProductionCountries []string               `protobuf:"bytes,5,rep,name=production_countries,json=productionCountries" json:"production_countries,omitempty"`
	ReleaseYear         *uint32                `protobuf:"varint,6,req,name=release_year,json=releaseYear" json:"release_year,omitempty"`
	Revenue             *float64               `protobuf:"fixed64,7,req,name=revenue" json:"revenue,omitempty"`
	Title               *string                `protobuf:"bytes,8,req,name=title" json:"title,omitempty"`
	Eof                 *bool                  `protobuf:"varint,9,opt,name=eof" json:"eof,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MovieSanit) Reset() {
	*x = MovieSanit{}
	mi := &file_movie_sanit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieSanit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieSanit) ProtoMessage() {}

func (x *MovieSanit) ProtoReflect() protoreflect.Message {
	mi := &file_movie_sanit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieSanit.ProtoReflect.Descriptor instead.
func (*MovieSanit) Descriptor() ([]byte, []int) {
	return file_movie_sanit_proto_rawDescGZIP(), []int{0}
}

func (x *MovieSanit) GetBudget() int32 {
	if x != nil && x.Budget != nil {
		return *x.Budget
	}
	return 0
}

func (x *MovieSanit) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieSanit) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MovieSanit) GetOverview() string {
	if x != nil && x.Overview != nil {
		return *x.Overview
	}
	return ""
}

func (x *MovieSanit) GetProductionCountries() []string {
	if x != nil {
		return x.ProductionCountries
	}
	return nil
}

func (x *MovieSanit) GetReleaseYear() uint32 {
	if x != nil && x.ReleaseYear != nil {
		return *x.ReleaseYear
	}
	return 0
}

func (x *MovieSanit) GetRevenue() float64 {
	if x != nil && x.Revenue != nil {
		return *x.Revenue
	}
	return 0
}

func (x *MovieSanit) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MovieSanit) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_movie_sanit_proto protoreflect.FileDescriptor

const file_movie_sanit_proto_rawDesc = "" +
	"\n" +
	"\x11movie_sanit.proto\"\x80\x02\n" +
	"\n" +
	"MovieSanit\x12\x16\n" +
	"\x06budget\x18\x01 \x02(\x05R\x06budget\x12\x16\n" +
	"\x06genres\x18\x02 \x03(\tR\x06genres\x12\x0e\n" +
	"\x02id\x18\x03 \x02(\x05R\x02id\x12\x1a\n" +
	"\boverview\x18\x04 \x02(\tR\boverview\x121\n" +
	"\x14production_countries\x18\x05 \x03(\tR\x13productionCountries\x12!\n" +
	"\frelease_year\x18\x06 \x02(\rR\vreleaseYear\x12\x18\n" +
	"\arevenue\x18\a \x02(\x01R\arevenue\x12\x14\n" +
	"\x05title\x18\b \x02(\tR\x05title\x12\x10\n" +
	"\x03eof\x18\t \x01(\bR\x03eofB\vZ\t./protopb"

var (
	file_movie_sanit_proto_rawDescOnce sync.Once
	file_movie_sanit_proto_rawDescData []byte
)

func file_movie_sanit_proto_rawDescGZIP() []byte {
	file_movie_sanit_proto_rawDescOnce.Do(func() {
		file_movie_sanit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_sanit_proto_rawDesc), len(file_movie_sanit_proto_rawDesc)))
	})
	return file_movie_sanit_proto_rawDescData
}

var file_movie_sanit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_movie_sanit_proto_goTypes = []any{
	(*MovieSanit)(nil), // 0: MovieSanit
}
var file_movie_sanit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movie_sanit_proto_init() }
func file_movie_sanit_proto_init() {
	if File_movie_sanit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_sanit_proto_rawDesc), len(file_movie_sanit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_movie_sanit_proto_goTypes,
		DependencyIndexes: file_movie_sanit_proto_depIdxs,
		MessageInfos:      file_movie_sanit_proto_msgTypes,
	}.Build()
	File_movie_sanit_proto = out.File
	file_movie_sanit_proto_goTypes = nil
	file_movie_sanit_proto_depIdxs = nil
}
