// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: movie.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Budget              *int64                 `protobuf:"varint,3,req,name=budget" json:"budget,omitempty"`
	Genres              *string                `protobuf:"bytes,4,req,name=genres" json:"genres,omitempty"`
	Id                  *int32                 `protobuf:"varint,6,req,name=id" json:"id,omitempty"`
	Overview            *string                `protobuf:"bytes,10,req,name=overview" json:"overview,omitempty"`
	ProductionCountries *string                `protobuf:"bytes,14,req,name=production_countries,json=productionCountries" json:"production_countries,omitempty"`
	ReleaseDate         *string                `protobuf:"bytes,15,req,name=release_date,json=releaseDate" json:"release_date,omitempty"`
	Revenue             *float64               `protobuf:"fixed64,16,req,name=revenue" json:"revenue,omitempty"`
	SpokenLanguages     *string                `protobuf:"bytes,18,req,name=spoken_languages,json=spokenLanguages" json:"spoken_languages,omitempty"`
	Title               *string                `protobuf:"bytes,21,req,name=title" json:"title,omitempty"`
	ClientId            *string                `protobuf:"bytes,25,opt,name=clientId" json:"clientId,omitempty"`
	Eof                 *bool                  `protobuf:"varint,26,opt,name=eof" json:"eof,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetBudget() int64 {
	if x != nil && x.Budget != nil {
		return *x.Budget
	}
	return 0
}

func (x *Movie) GetGenres() string {
	if x != nil && x.Genres != nil {
		return *x.Genres
	}
	return ""
}

func (x *Movie) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Movie) GetOverview() string {
	if x != nil && x.Overview != nil {
		return *x.Overview
	}
	return ""
}

func (x *Movie) GetProductionCountries() string {
	if x != nil && x.ProductionCountries != nil {
		return *x.ProductionCountries
	}
	return ""
}

func (x *Movie) GetReleaseDate() string {
	if x != nil && x.ReleaseDate != nil {
		return *x.ReleaseDate
	}
	return ""
}

func (x *Movie) GetRevenue() float64 {
	if x != nil && x.Revenue != nil {
		return *x.Revenue
	}
	return 0
}

func (x *Movie) GetSpokenLanguages() string {
	if x != nil && x.SpokenLanguages != nil {
		return *x.SpokenLanguages
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Movie) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Movie) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_movie_proto protoreflect.FileDescriptor

const file_movie_proto_rawDesc = "" +
	"\n" +
	"\vmovie.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc2\x02\n" +
	"\x05Movie\x12\x16\n" +
	"\x06budget\x18\x03 \x02(\x03R\x06budget\x12\x16\n" +
	"\x06genres\x18\x04 \x02(\tR\x06genres\x12\x0e\n" +
	"\x02id\x18\x06 \x02(\x05R\x02id\x12\x1a\n" +
	"\boverview\x18\n" +
	" \x02(\tR\boverview\x121\n" +
	"\x14production_countries\x18\x0e \x02(\tR\x13productionCountries\x12!\n" +
	"\frelease_date\x18\x0f \x02(\tR\vreleaseDate\x12\x18\n" +
	"\arevenue\x18\x10 \x02(\x01R\arevenue\x12)\n" +
	"\x10spoken_languages\x18\x12 \x02(\tR\x0fspokenLanguages\x12\x14\n" +
	"\x05title\x18\x15 \x02(\tR\x05title\x12\x1a\n" +
	"\bclientId\x18\x19 \x01(\tR\bclientId\x12\x10\n" +
	"\x03eof\x18\x1a \x01(\bR\x03eof2@\n" +
	"\fMovieService\x120\n" +
	"\fStreamMovies\x12\x06.Movie\x1a\x16.google.protobuf.Empty(\x01B\vZ\t./protopb"

var (
	file_movie_proto_rawDescOnce sync.Once
	file_movie_proto_rawDescData []byte
)

func file_movie_proto_rawDescGZIP() []byte {
	file_movie_proto_rawDescOnce.Do(func() {
		file_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)))
	})
	return file_movie_proto_rawDescData
}

var file_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_movie_proto_goTypes = []any{
	(*Movie)(nil),         // 0: Movie
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_movie_proto_depIdxs = []int32{
	0, // 0: MovieService.StreamMovies:input_type -> Movie
	1, // 1: MovieService.StreamMovies:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movie_proto_init() }
func file_movie_proto_init() {
	if File_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_proto_goTypes,
		DependencyIndexes: file_movie_proto_depIdxs,
		MessageInfos:      file_movie_proto_msgTypes,
	}.Build()
	File_movie_proto = out.File
	file_movie_proto_goTypes = nil
	file_movie_proto_depIdxs = nil
}
