// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: movie.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Adult               *bool                  `protobuf:"varint,1,req,name=adult" json:"adult,omitempty"`
	BelongsToCollection *string                `protobuf:"bytes,2,opt,name=belongs_to_collection,json=belongsToCollection" json:"belongs_to_collection,omitempty"`
	Budget              *int32                 `protobuf:"varint,3,req,name=budget" json:"budget,omitempty"`
	Genres              *string                `protobuf:"bytes,4,req,name=genres" json:"genres,omitempty"`
	Homepage            *string                `protobuf:"bytes,5,opt,name=homepage" json:"homepage,omitempty"`
	Id                  *int32                 `protobuf:"varint,6,req,name=id" json:"id,omitempty"`
	ImdbId              *string                `protobuf:"bytes,7,req,name=imdb_id,json=imdbId" json:"imdb_id,omitempty"`
	OriginalLanguage    *string                `protobuf:"bytes,8,req,name=original_language,json=originalLanguage" json:"original_language,omitempty"`
	OriginalTitle       *string                `protobuf:"bytes,9,req,name=original_title,json=originalTitle" json:"original_title,omitempty"`
	Overview            *string                `protobuf:"bytes,10,req,name=overview" json:"overview,omitempty"`
	Popularity          *float32               `protobuf:"fixed32,11,req,name=popularity" json:"popularity,omitempty"`
	PosterPath          *string                `protobuf:"bytes,12,req,name=poster_path,json=posterPath" json:"poster_path,omitempty"`
	ProductionCompanies *string                `protobuf:"bytes,13,req,name=production_companies,json=productionCompanies" json:"production_companies,omitempty"`
	ProductionCountries *string                `protobuf:"bytes,14,req,name=production_countries,json=productionCountries" json:"production_countries,omitempty"`
	ReleaseDate         *string                `protobuf:"bytes,15,req,name=release_date,json=releaseDate" json:"release_date,omitempty"`
	Revenue             *float64               `protobuf:"fixed64,16,req,name=revenue" json:"revenue,omitempty"`
	Runtime             *float64               `protobuf:"fixed64,17,req,name=runtime" json:"runtime,omitempty"`
	SpokenLanguages     *string                `protobuf:"bytes,18,req,name=spoken_languages,json=spokenLanguages" json:"spoken_languages,omitempty"`
	Status              *string                `protobuf:"bytes,19,req,name=status" json:"status,omitempty"`
	Tagline             *string                `protobuf:"bytes,20,opt,name=tagline" json:"tagline,omitempty"`
	Title               *string                `protobuf:"bytes,21,req,name=title" json:"title,omitempty"`
	Video               *bool                  `protobuf:"varint,22,req,name=video" json:"video,omitempty"`
	VoteAverage         *float64               `protobuf:"fixed64,23,req,name=vote_average,json=voteAverage" json:"vote_average,omitempty"`
	VoteCount           *int32                 `protobuf:"varint,24,req,name=vote_count,json=voteCount" json:"vote_count,omitempty"`
	ClientId            *string                `protobuf:"bytes,25,opt,name=clientId" json:"clientId,omitempty"`
	Eof                 *bool                  `protobuf:"varint,26,opt,name=eof" json:"eof,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetAdult() bool {
	if x != nil && x.Adult != nil {
		return *x.Adult
	}
	return false
}

func (x *Movie) GetBelongsToCollection() string {
	if x != nil && x.BelongsToCollection != nil {
		return *x.BelongsToCollection
	}
	return ""
}

func (x *Movie) GetBudget() int32 {
	if x != nil && x.Budget != nil {
		return *x.Budget
	}
	return 0
}

func (x *Movie) GetGenres() string {
	if x != nil && x.Genres != nil {
		return *x.Genres
	}
	return ""
}

func (x *Movie) GetHomepage() string {
	if x != nil && x.Homepage != nil {
		return *x.Homepage
	}
	return ""
}

func (x *Movie) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Movie) GetImdbId() string {
	if x != nil && x.ImdbId != nil {
		return *x.ImdbId
	}
	return ""
}

func (x *Movie) GetOriginalLanguage() string {
	if x != nil && x.OriginalLanguage != nil {
		return *x.OriginalLanguage
	}
	return ""
}

func (x *Movie) GetOriginalTitle() string {
	if x != nil && x.OriginalTitle != nil {
		return *x.OriginalTitle
	}
	return ""
}

func (x *Movie) GetOverview() string {
	if x != nil && x.Overview != nil {
		return *x.Overview
	}
	return ""
}

func (x *Movie) GetPopularity() float32 {
	if x != nil && x.Popularity != nil {
		return *x.Popularity
	}
	return 0
}

func (x *Movie) GetPosterPath() string {
	if x != nil && x.PosterPath != nil {
		return *x.PosterPath
	}
	return ""
}

func (x *Movie) GetProductionCompanies() string {
	if x != nil && x.ProductionCompanies != nil {
		return *x.ProductionCompanies
	}
	return ""
}

func (x *Movie) GetProductionCountries() string {
	if x != nil && x.ProductionCountries != nil {
		return *x.ProductionCountries
	}
	return ""
}

func (x *Movie) GetReleaseDate() string {
	if x != nil && x.ReleaseDate != nil {
		return *x.ReleaseDate
	}
	return ""
}

func (x *Movie) GetRevenue() float64 {
	if x != nil && x.Revenue != nil {
		return *x.Revenue
	}
	return 0
}

func (x *Movie) GetRuntime() float64 {
	if x != nil && x.Runtime != nil {
		return *x.Runtime
	}
	return 0
}

func (x *Movie) GetSpokenLanguages() string {
	if x != nil && x.SpokenLanguages != nil {
		return *x.SpokenLanguages
	}
	return ""
}

func (x *Movie) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Movie) GetTagline() string {
	if x != nil && x.Tagline != nil {
		return *x.Tagline
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Movie) GetVideo() bool {
	if x != nil && x.Video != nil {
		return *x.Video
	}
	return false
}

func (x *Movie) GetVoteAverage() float64 {
	if x != nil && x.VoteAverage != nil {
		return *x.VoteAverage
	}
	return 0
}

func (x *Movie) GetVoteCount() int32 {
	if x != nil && x.VoteCount != nil {
		return *x.VoteCount
	}
	return 0
}

func (x *Movie) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Movie) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_movie_proto protoreflect.FileDescriptor

const file_movie_proto_rawDesc = "" +
	"\n" +
	"\vmovie.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xad\x06\n" +
	"\x05Movie\x12\x14\n" +
	"\x05adult\x18\x01 \x02(\bR\x05adult\x122\n" +
	"\x15belongs_to_collection\x18\x02 \x01(\tR\x13belongsToCollection\x12\x16\n" +
	"\x06budget\x18\x03 \x02(\x05R\x06budget\x12\x16\n" +
	"\x06genres\x18\x04 \x02(\tR\x06genres\x12\x1a\n" +
	"\bhomepage\x18\x05 \x01(\tR\bhomepage\x12\x0e\n" +
	"\x02id\x18\x06 \x02(\x05R\x02id\x12\x17\n" +
	"\aimdb_id\x18\a \x02(\tR\x06imdbId\x12+\n" +
	"\x11original_language\x18\b \x02(\tR\x10originalLanguage\x12%\n" +
	"\x0eoriginal_title\x18\t \x02(\tR\roriginalTitle\x12\x1a\n" +
	"\boverview\x18\n" +
	" \x02(\tR\boverview\x12\x1e\n" +
	"\n" +
	"popularity\x18\v \x02(\x02R\n" +
	"popularity\x12\x1f\n" +
	"\vposter_path\x18\f \x02(\tR\n" +
	"posterPath\x121\n" +
	"\x14production_companies\x18\r \x02(\tR\x13productionCompanies\x121\n" +
	"\x14production_countries\x18\x0e \x02(\tR\x13productionCountries\x12!\n" +
	"\frelease_date\x18\x0f \x02(\tR\vreleaseDate\x12\x18\n" +
	"\arevenue\x18\x10 \x02(\x01R\arevenue\x12\x18\n" +
	"\aruntime\x18\x11 \x02(\x01R\aruntime\x12)\n" +
	"\x10spoken_languages\x18\x12 \x02(\tR\x0fspokenLanguages\x12\x16\n" +
	"\x06status\x18\x13 \x02(\tR\x06status\x12\x18\n" +
	"\atagline\x18\x14 \x01(\tR\atagline\x12\x14\n" +
	"\x05title\x18\x15 \x02(\tR\x05title\x12\x14\n" +
	"\x05video\x18\x16 \x02(\bR\x05video\x12!\n" +
	"\fvote_average\x18\x17 \x02(\x01R\vvoteAverage\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x18 \x02(\x05R\tvoteCount\x12\x1a\n" +
	"\bclientId\x18\x19 \x01(\tR\bclientId\x12\x10\n" +
	"\x03eof\x18\x1a \x01(\bR\x03eof2@\n" +
	"\fMovieService\x120\n" +
	"\fStreamMovies\x12\x06.Movie\x1a\x16.google.protobuf.Empty(\x01B\vZ\t./protopb"

var (
	file_movie_proto_rawDescOnce sync.Once
	file_movie_proto_rawDescData []byte
)

func file_movie_proto_rawDescGZIP() []byte {
	file_movie_proto_rawDescOnce.Do(func() {
		file_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)))
	})
	return file_movie_proto_rawDescData
}

var file_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_movie_proto_goTypes = []any{
	(*Movie)(nil),         // 0: Movie
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_movie_proto_depIdxs = []int32{
	0, // 0: MovieService.StreamMovies:input_type -> Movie
	1, // 1: MovieService.StreamMovies:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movie_proto_init() }
func file_movie_proto_init() {
	if File_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_proto_goTypes,
		DependencyIndexes: file_movie_proto_depIdxs,
		MessageInfos:      file_movie_proto_msgTypes,
	}.Build()
	File_movie_proto = out.File
	file_movie_proto_goTypes = nil
	file_movie_proto_depIdxs = nil
}
