// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rating.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       *int64                 `protobuf:"varint,1,req,name=movieId" json:"movieId,omitempty"`
	Rating        *float32               `protobuf:"fixed32,2,req,name=rating" json:"rating,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,opt,name=clientId" json:"clientId,omitempty"`
	MessageId     *int64                 `protobuf:"varint,5,opt,name=messageId" json:"messageId,omitempty"`
	Eof           *bool                  `protobuf:"varint,6,opt,name=eof" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{0}
}

func (x *Rating) GetMovieId() int64 {
	if x != nil && x.MovieId != nil {
		return *x.MovieId
	}
	return 0
}

func (x *Rating) GetRating() float32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *Rating) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Rating) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Rating) GetMessageId() int64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *Rating) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_rating_proto protoreflect.FileDescriptor

const file_rating_proto_rawDesc = "" +
	"\n" +
	"\frating.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa4\x01\n" +
	"\x06Rating\x12\x18\n" +
	"\amovieId\x18\x01 \x02(\x03R\amovieId\x12\x16\n" +
	"\x06rating\x18\x02 \x02(\x02R\x06rating\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x02(\x03R\ttimestamp\x12\x1a\n" +
	"\bclientId\x18\x04 \x01(\tR\bclientId\x12\x1c\n" +
	"\tmessageId\x18\x05 \x01(\x03R\tmessageId\x12\x10\n" +
	"\x03eof\x18\x06 \x01(\bR\x03eof2C\n" +
	"\rRatingService\x122\n" +
	"\rStreamRatings\x12\a.Rating\x1a\x16.google.protobuf.Empty(\x01B\vZ\t./protopb"

var (
	file_rating_proto_rawDescOnce sync.Once
	file_rating_proto_rawDescData []byte
)

func file_rating_proto_rawDescGZIP() []byte {
	file_rating_proto_rawDescOnce.Do(func() {
		file_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rating_proto_rawDesc), len(file_rating_proto_rawDesc)))
	})
	return file_rating_proto_rawDescData
}

var file_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rating_proto_goTypes = []any{
	(*Rating)(nil),        // 0: Rating
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_rating_proto_depIdxs = []int32{
	0, // 0: RatingService.StreamRatings:input_type -> Rating
	1, // 1: RatingService.StreamRatings:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rating_proto_init() }
func file_rating_proto_init() {
	if File_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rating_proto_rawDesc), len(file_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rating_proto_goTypes,
		DependencyIndexes: file_rating_proto_depIdxs,
		MessageInfos:      file_rating_proto_msgTypes,
	}.Build()
	File_rating_proto = out.File
	file_rating_proto_goTypes = nil
	file_rating_proto_depIdxs = nil
}
