// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: report.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer1       *Answer1               `protobuf:"bytes,1,req,name=answer1" json:"answer1,omitempty"`
	Answer2       *Answer2               `protobuf:"bytes,2,req,name=answer2" json:"answer2,omitempty"`
	Answer3       *Answer3               `protobuf:"bytes,3,req,name=answer3" json:"answer3,omitempty"`
	Answer4       *Answer4               `protobuf:"bytes,4,req,name=answer4" json:"answer4,omitempty"`
	Answer5       *Answer5               `protobuf:"bytes,5,req,name=answer5" json:"answer5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *ReportResponse) GetAnswer1() *Answer1 {
	if x != nil {
		return x.Answer1
	}
	return nil
}

func (x *ReportResponse) GetAnswer2() *Answer2 {
	if x != nil {
		return x.Answer2
	}
	return nil
}

func (x *ReportResponse) GetAnswer3() *Answer3 {
	if x != nil {
		return x.Answer3
	}
	return nil
}

func (x *ReportResponse) GetAnswer4() *Answer4 {
	if x != nil {
		return x.Answer4
	}
	return nil
}

func (x *ReportResponse) GetAnswer5() *Answer5 {
	if x != nil {
		return x.Answer5
	}
	return nil
}

type Answer1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*MovieEntry          `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer1) Reset() {
	*x = Answer1{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer1) ProtoMessage() {}

func (x *Answer1) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer1.ProtoReflect.Descriptor instead.
func (*Answer1) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *Answer1) GetMovies() []*MovieEntry {
	if x != nil {
		return x.Movies
	}
	return nil
}

type MovieEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,req,name=title" json:"title,omitempty"`
	Genres        []string               `protobuf:"bytes,3,rep,name=genres" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieEntry) Reset() {
	*x = MovieEntry{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieEntry) ProtoMessage() {}

func (x *MovieEntry) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieEntry.ProtoReflect.Descriptor instead.
func (*MovieEntry) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *MovieEntry) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MovieEntry) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MovieEntry) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type Answer2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*CountryEntry        `protobuf:"bytes,1,rep,name=countries" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer2) Reset() {
	*x = Answer2{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer2) ProtoMessage() {}

func (x *Answer2) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer2.ProtoReflect.Descriptor instead.
func (*Answer2) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *Answer2) GetCountries() []*CountryEntry {
	if x != nil {
		return x.Countries
	}
	return nil
}

type CountryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Budget        *int32                 `protobuf:"varint,2,req,name=budget" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryEntry) Reset() {
	*x = CountryEntry{}
	mi := &file_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryEntry) ProtoMessage() {}

func (x *CountryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryEntry.ProtoReflect.Descriptor instead.
func (*CountryEntry) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{4}
}

func (x *CountryEntry) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CountryEntry) GetBudget() int32 {
	if x != nil && x.Budget != nil {
		return *x.Budget
	}
	return 0
}

type Answer3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *MovieRating           `protobuf:"bytes,1,req,name=min" json:"min,omitempty"`
	Max           *MovieRating           `protobuf:"bytes,2,req,name=max" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer3) Reset() {
	*x = Answer3{}
	mi := &file_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer3) ProtoMessage() {}

func (x *Answer3) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer3.ProtoReflect.Descriptor instead.
func (*Answer3) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{5}
}

func (x *Answer3) GetMin() *MovieRating {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Answer3) GetMax() *MovieRating {
	if x != nil {
		return x.Max
	}
	return nil
}

type MovieRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,req,name=title" json:"title,omitempty"`
	Rating        *float64               `protobuf:"fixed64,3,req,name=rating" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieRating) Reset() {
	*x = MovieRating{}
	mi := &file_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieRating) ProtoMessage() {}

func (x *MovieRating) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieRating.ProtoReflect.Descriptor instead.
func (*MovieRating) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{6}
}

func (x *MovieRating) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MovieRating) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MovieRating) GetRating() float64 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

type Answer4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*ActorEntry          `protobuf:"bytes,1,rep,name=actors" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer4) Reset() {
	*x = Answer4{}
	mi := &file_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer4) ProtoMessage() {}

func (x *Answer4) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer4.ProtoReflect.Descriptor instead.
func (*Answer4) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{7}
}

func (x *Answer4) GetActors() []*ActorEntry {
	if x != nil {
		return x.Actors
	}
	return nil
}

type ActorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Count         *int64                 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorEntry) Reset() {
	*x = ActorEntry{}
	mi := &file_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEntry) ProtoMessage() {}

func (x *ActorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEntry.ProtoReflect.Descriptor instead.
func (*ActorEntry) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{8}
}

func (x *ActorEntry) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ActorEntry) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ActorEntry) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type Answer5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positive      *SentimentScore        `protobuf:"bytes,1,req,name=positive" json:"positive,omitempty"`
	Negative      *SentimentScore        `protobuf:"bytes,2,req,name=negative" json:"negative,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer5) Reset() {
	*x = Answer5{}
	mi := &file_report_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer5) ProtoMessage() {}

func (x *Answer5) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer5.ProtoReflect.Descriptor instead.
func (*Answer5) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{9}
}

func (x *Answer5) GetPositive() *SentimentScore {
	if x != nil {
		return x.Positive
	}
	return nil
}

func (x *Answer5) GetNegative() *SentimentScore {
	if x != nil {
		return x.Negative
	}
	return nil
}

type SentimentScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Score         *float32               `protobuf:"fixed32,2,req,name=score" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentimentScore) Reset() {
	*x = SentimentScore{}
	mi := &file_report_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentScore) ProtoMessage() {}

func (x *SentimentScore) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentScore.ProtoReflect.Descriptor instead.
func (*SentimentScore) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{10}
}

func (x *SentimentScore) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *SentimentScore) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc4\x01\n" +
	"\x0eReportResponse\x12\"\n" +
	"\aanswer1\x18\x01 \x02(\v2\b.Answer1R\aanswer1\x12\"\n" +
	"\aanswer2\x18\x02 \x02(\v2\b.Answer2R\aanswer2\x12\"\n" +
	"\aanswer3\x18\x03 \x02(\v2\b.Answer3R\aanswer3\x12\"\n" +
	"\aanswer4\x18\x04 \x02(\v2\b.Answer4R\aanswer4\x12\"\n" +
	"\aanswer5\x18\x05 \x02(\v2\b.Answer5R\aanswer5\".\n" +
	"\aAnswer1\x12#\n" +
	"\x06movies\x18\x01 \x03(\v2\v.MovieEntryR\x06movies\"J\n" +
	"\n" +
	"MovieEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x02(\tR\x05title\x12\x16\n" +
	"\x06genres\x18\x03 \x03(\tR\x06genres\"6\n" +
	"\aAnswer2\x12+\n" +
	"\tcountries\x18\x01 \x03(\v2\r.CountryEntryR\tcountries\":\n" +
	"\fCountryEntry\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x16\n" +
	"\x06budget\x18\x02 \x02(\x05R\x06budget\"I\n" +
	"\aAnswer3\x12\x1e\n" +
	"\x03min\x18\x01 \x02(\v2\f.MovieRatingR\x03min\x12\x1e\n" +
	"\x03max\x18\x02 \x02(\v2\f.MovieRatingR\x03max\"K\n" +
	"\vMovieRating\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x02(\tR\x05title\x12\x16\n" +
	"\x06rating\x18\x03 \x02(\x01R\x06rating\".\n" +
	"\aAnswer4\x12#\n" +
	"\x06actors\x18\x01 \x03(\v2\v.ActorEntryR\x06actors\"F\n" +
	"\n" +
	"ActorEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x02(\x03R\x05count\"c\n" +
	"\aAnswer5\x12+\n" +
	"\bpositive\x18\x01 \x02(\v2\x0f.SentimentScoreR\bpositive\x12+\n" +
	"\bnegative\x18\x02 \x02(\v2\x0f.SentimentScoreR\bnegative\":\n" +
	"\x0eSentimentScore\x12\x12\n" +
	"\x04type\x18\x01 \x02(\tR\x04type\x12\x14\n" +
	"\x05score\x18\x02 \x02(\x02R\x05score2E\n" +
	"\rReportService\x124\n" +
	"\tGetReport\x12\x16.google.protobuf.Empty\x1a\x0f.ReportResponseB\vZ\t./protopb"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_report_proto_goTypes = []any{
	(*ReportResponse)(nil), // 0: ReportResponse
	(*Answer1)(nil),        // 1: Answer1
	(*MovieEntry)(nil),     // 2: MovieEntry
	(*Answer2)(nil),        // 3: Answer2
	(*CountryEntry)(nil),   // 4: CountryEntry
	(*Answer3)(nil),        // 5: Answer3
	(*MovieRating)(nil),    // 6: MovieRating
	(*Answer4)(nil),        // 7: Answer4
	(*ActorEntry)(nil),     // 8: ActorEntry
	(*Answer5)(nil),        // 9: Answer5
	(*SentimentScore)(nil), // 10: SentimentScore
	(*emptypb.Empty)(nil),  // 11: google.protobuf.Empty
}
var file_report_proto_depIdxs = []int32{
	1,  // 0: ReportResponse.answer1:type_name -> Answer1
	3,  // 1: ReportResponse.answer2:type_name -> Answer2
	5,  // 2: ReportResponse.answer3:type_name -> Answer3
	7,  // 3: ReportResponse.answer4:type_name -> Answer4
	9,  // 4: ReportResponse.answer5:type_name -> Answer5
	2,  // 5: Answer1.movies:type_name -> MovieEntry
	4,  // 6: Answer2.countries:type_name -> CountryEntry
	6,  // 7: Answer3.min:type_name -> MovieRating
	6,  // 8: Answer3.max:type_name -> MovieRating
	8,  // 9: Answer4.actors:type_name -> ActorEntry
	10, // 10: Answer5.positive:type_name -> SentimentScore
	10, // 11: Answer5.negative:type_name -> SentimentScore
	11, // 12: ReportService.GetReport:input_type -> google.protobuf.Empty
	0,  // 13: ReportService.GetReport:output_type -> ReportResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
