// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: top_10.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Top10 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	ProfilePaths  []string               `protobuf:"bytes,2,rep,name=profilePaths" json:"profilePaths,omitempty"`
	CountMovies   []int64                `protobuf:"varint,3,rep,name=countMovies" json:"countMovies,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,req,name=clientId" json:"clientId,omitempty"`
	MessageId     *int64                 `protobuf:"varint,5,req,name=messageId" json:"messageId,omitempty"`
	SourceId      *string                `protobuf:"bytes,6,opt,name=sourceId" json:"sourceId,omitempty"`
	Eof           *bool                  `protobuf:"varint,7,opt,name=eof" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Top10) Reset() {
	*x = Top10{}
	mi := &file_top_10_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Top10) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top10) ProtoMessage() {}

func (x *Top10) ProtoReflect() protoreflect.Message {
	mi := &file_top_10_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top10.ProtoReflect.Descriptor instead.
func (*Top10) Descriptor() ([]byte, []int) {
	return file_top_10_proto_rawDescGZIP(), []int{0}
}

func (x *Top10) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Top10) GetProfilePaths() []string {
	if x != nil {
		return x.ProfilePaths
	}
	return nil
}

func (x *Top10) GetCountMovies() []int64 {
	if x != nil {
		return x.CountMovies
	}
	return nil
}

func (x *Top10) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Top10) GetMessageId() int64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *Top10) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *Top10) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_top_10_proto protoreflect.FileDescriptor

const file_top_10_proto_rawDesc = "" +
	"\n" +
	"\ftop_10.proto\"\xcb\x01\n" +
	"\x05Top10\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\"\n" +
	"\fprofilePaths\x18\x02 \x03(\tR\fprofilePaths\x12 \n" +
	"\vcountMovies\x18\x03 \x03(\x03R\vcountMovies\x12\x1a\n" +
	"\bclientId\x18\x04 \x02(\tR\bclientId\x12\x1c\n" +
	"\tmessageId\x18\x05 \x02(\x03R\tmessageId\x12\x1a\n" +
	"\bsourceId\x18\x06 \x01(\tR\bsourceId\x12\x10\n" +
	"\x03eof\x18\a \x01(\bR\x03eofB\vZ\t./protopb"

var (
	file_top_10_proto_rawDescOnce sync.Once
	file_top_10_proto_rawDescData []byte
)

func file_top_10_proto_rawDescGZIP() []byte {
	file_top_10_proto_rawDescOnce.Do(func() {
		file_top_10_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_top_10_proto_rawDesc), len(file_top_10_proto_rawDesc)))
	})
	return file_top_10_proto_rawDescData
}

var file_top_10_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_top_10_proto_goTypes = []any{
	(*Top10)(nil), // 0: Top10
}
var file_top_10_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_top_10_proto_init() }
func file_top_10_proto_init() {
	if File_top_10_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_top_10_proto_rawDesc), len(file_top_10_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_top_10_proto_goTypes,
		DependencyIndexes: file_top_10_proto_depIdxs,
		MessageInfos:      file_top_10_proto_msgTypes,
	}.Build()
	File_top_10_proto = out.File
	file_top_10_proto_goTypes = nil
	file_top_10_proto_depIdxs = nil
}
