// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: top_5_country.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Top5Country struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Budget              []int32                `protobuf:"varint,1,rep,name=budget" json:"budget,omitempty"`
	ProductionCountries []string               `protobuf:"bytes,2,rep,name=production_countries,json=productionCountries" json:"production_countries,omitempty"`
	ClientId            *string                `protobuf:"bytes,3,opt,name=clientId" json:"clientId,omitempty"`
	Eof                 *bool                  `protobuf:"varint,4,opt,name=eof" json:"eof,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Top5Country) Reset() {
	*x = Top5Country{}
	mi := &file_top_5_country_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Top5Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top5Country) ProtoMessage() {}

func (x *Top5Country) ProtoReflect() protoreflect.Message {
	mi := &file_top_5_country_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top5Country.ProtoReflect.Descriptor instead.
func (*Top5Country) Descriptor() ([]byte, []int) {
	return file_top_5_country_proto_rawDescGZIP(), []int{0}
}

func (x *Top5Country) GetBudget() []int32 {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *Top5Country) GetProductionCountries() []string {
	if x != nil {
		return x.ProductionCountries
	}
	return nil
}

func (x *Top5Country) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Top5Country) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_top_5_country_proto protoreflect.FileDescriptor

const file_top_5_country_proto_rawDesc = "" +
	"\n" +
	"\x13top_5_country.proto\"\x86\x01\n" +
	"\vTop5Country\x12\x16\n" +
	"\x06budget\x18\x01 \x03(\x05R\x06budget\x121\n" +
	"\x14production_countries\x18\x02 \x03(\tR\x13productionCountries\x12\x1a\n" +
	"\bclientId\x18\x03 \x01(\tR\bclientId\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eofB\vZ\t./protopb"

var (
	file_top_5_country_proto_rawDescOnce sync.Once
	file_top_5_country_proto_rawDescData []byte
)

func file_top_5_country_proto_rawDescGZIP() []byte {
	file_top_5_country_proto_rawDescOnce.Do(func() {
		file_top_5_country_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_top_5_country_proto_rawDesc), len(file_top_5_country_proto_rawDesc)))
	})
	return file_top_5_country_proto_rawDescData
}

var file_top_5_country_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_top_5_country_proto_goTypes = []any{
	(*Top5Country)(nil), // 0: Top5Country
}
var file_top_5_country_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_top_5_country_proto_init() }
func file_top_5_country_proto_init() {
	if File_top_5_country_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_top_5_country_proto_rawDesc), len(file_top_5_country_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_top_5_country_proto_goTypes,
		DependencyIndexes: file_top_5_country_proto_depIdxs,
		MessageInfos:      file_top_5_country_proto_msgTypes,
	}.Build()
	File_top_5_country_proto = out.File
	file_top_5_country_proto_goTypes = nil
	file_top_5_country_proto_depIdxs = nil
}
