// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: top_and_bottom_rating_avg.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopAndBottomRatingAvg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TitleTop        *string                `protobuf:"bytes,1,opt,name=title_top,json=titleTop" json:"title_top,omitempty"`
	TitleBottom     *string                `protobuf:"bytes,2,opt,name=title_bottom,json=titleBottom" json:"title_bottom,omitempty"`
	RatingAvgTop    *float64               `protobuf:"fixed64,3,opt,name=rating_avg_top,json=ratingAvgTop" json:"rating_avg_top,omitempty"`
	RatingAvgBottom *float64               `protobuf:"fixed64,4,opt,name=rating_avg_bottom,json=ratingAvgBottom" json:"rating_avg_bottom,omitempty"`
	Eof             *bool                  `protobuf:"varint,5,opt,name=eof" json:"eof,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TopAndBottomRatingAvg) Reset() {
	*x = TopAndBottomRatingAvg{}
	mi := &file_top_and_bottom_rating_avg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopAndBottomRatingAvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopAndBottomRatingAvg) ProtoMessage() {}

func (x *TopAndBottomRatingAvg) ProtoReflect() protoreflect.Message {
	mi := &file_top_and_bottom_rating_avg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopAndBottomRatingAvg.ProtoReflect.Descriptor instead.
func (*TopAndBottomRatingAvg) Descriptor() ([]byte, []int) {
	return file_top_and_bottom_rating_avg_proto_rawDescGZIP(), []int{0}
}

func (x *TopAndBottomRatingAvg) GetTitleTop() string {
	if x != nil && x.TitleTop != nil {
		return *x.TitleTop
	}
	return ""
}

func (x *TopAndBottomRatingAvg) GetTitleBottom() string {
	if x != nil && x.TitleBottom != nil {
		return *x.TitleBottom
	}
	return ""
}

func (x *TopAndBottomRatingAvg) GetRatingAvgTop() float64 {
	if x != nil && x.RatingAvgTop != nil {
		return *x.RatingAvgTop
	}
	return 0
}

func (x *TopAndBottomRatingAvg) GetRatingAvgBottom() float64 {
	if x != nil && x.RatingAvgBottom != nil {
		return *x.RatingAvgBottom
	}
	return 0
}

func (x *TopAndBottomRatingAvg) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_top_and_bottom_rating_avg_proto protoreflect.FileDescriptor

const file_top_and_bottom_rating_avg_proto_rawDesc = "" +
	"\n" +
	"\x1ftop_and_bottom_rating_avg.proto\"\xbb\x01\n" +
	"\x15TopAndBottomRatingAvg\x12\x1b\n" +
	"\ttitle_top\x18\x01 \x01(\tR\btitleTop\x12!\n" +
	"\ftitle_bottom\x18\x02 \x01(\tR\vtitleBottom\x12$\n" +
	"\x0erating_avg_top\x18\x03 \x01(\x01R\fratingAvgTop\x12*\n" +
	"\x11rating_avg_bottom\x18\x04 \x01(\x01R\x0fratingAvgBottom\x12\x10\n" +
	"\x03eof\x18\x05 \x01(\bR\x03eofB\vZ\t./protopb"

var (
	file_top_and_bottom_rating_avg_proto_rawDescOnce sync.Once
	file_top_and_bottom_rating_avg_proto_rawDescData []byte
)

func file_top_and_bottom_rating_avg_proto_rawDescGZIP() []byte {
	file_top_and_bottom_rating_avg_proto_rawDescOnce.Do(func() {
		file_top_and_bottom_rating_avg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_top_and_bottom_rating_avg_proto_rawDesc), len(file_top_and_bottom_rating_avg_proto_rawDesc)))
	})
	return file_top_and_bottom_rating_avg_proto_rawDescData
}

var file_top_and_bottom_rating_avg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_top_and_bottom_rating_avg_proto_goTypes = []any{
	(*TopAndBottomRatingAvg)(nil), // 0: TopAndBottomRatingAvg
}
var file_top_and_bottom_rating_avg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_top_and_bottom_rating_avg_proto_init() }
func file_top_and_bottom_rating_avg_proto_init() {
	if File_top_and_bottom_rating_avg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_top_and_bottom_rating_avg_proto_rawDesc), len(file_top_and_bottom_rating_avg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_top_and_bottom_rating_avg_proto_goTypes,
		DependencyIndexes: file_top_and_bottom_rating_avg_proto_depIdxs,
		MessageInfos:      file_top_and_bottom_rating_avg_proto_msgTypes,
	}.Build()
	File_top_and_bottom_rating_avg_proto = out.File
	file_top_and_bottom_rating_avg_proto_goTypes = nil
	file_top_and_bottom_rating_avg_proto_depIdxs = nil
}
